name: Post Deployment API Test

on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: api-tests
        run: npm install

      - name: Wait for Railway Deployment
        run: sleep 120

      - name: Run API Tests
        working-directory: api-tests
        run: npm test
